pipelines:
  test_phase: # name of pipeline
    group: spring_gocd_test
    materials:
      gocd_test: # name of my git
        git: https://github.com/khangphan-tw/spring_gocd_test.git
        branch: master
    stages:
      - testing: # name of stage
          clean_workspace: true
          jobs:
            unit_test:
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - "clean"
                      - "install"
                      - "-DskipIntegrationTests"
                    run_if: passed
            integration_test: # name of job
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - "clean"
                      - "install"
                      - "-DskipUnitTests"
                    run_if: passed
  # second pipeline
  run_app:
    group: spring_gocd_test
    materials:
      #      gocd_test:
      #        git: https://github.com/khangphan-tw/gocd_test.git
      #        branch: main
      myupstream:
        pipeline: test_phase
        stage: testing
    stages:
      - run_spring_boot_app:
          clean_workspace: true
          jobs:
            run:
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - "org.springframework.boot:spring-boot-maven-plugin:run"
                    run_if: passed